version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04-curl
    steps:
      - checkout
      - restore_cache:
          key: v1.14
      - run: 
          command: |
            set -xe
            sudo apt-get -yq update
            sudo apt-get -yq install r-base libboost-all-dev
            sudo apt-get clean
            sudo rm -rf /var/lib/apt/lists/*
            mkdir -p $HOME/.local
            if [ ! -d "$HOME/.local/lib" ] ; then 
              curl -skL https://github.com/lballabio/QuantLib/releases/download/QuantLib-v1.14/QuantLib-1.14.tar.gz | tar zxf -
              (cd QuantLib-1.14 ; ./autogen.sh ; ./configure --prefix=$HOME/.local --enable-intraday ; make install)
            fi
            sudo Rscript -e 'install.packages("RQuantLib", dependencies=TRUE)'
            curl -skL https://github.com/eddelbuettel/rquantlib/archive/master.zip -o rquantlib.zip
            unzip -o rquantlib.zip
            rm -f rquantlib.zip
#            (cd rquantlib-master ; R CMD build . ; sudo R CMD INSTALL RQuantLib*.gz)
            (cd rquantlib-master/tests ; LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local Rscript RQuantlib.R)
      - save_cache:
          key: v1.14
          paths: 
            - ~/.local
