version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04-curl
    steps:
      - checkout
      - run: 
          command: |
            set -xe
            sudo apt-get -yq update
            sudo apt-get -yq install r-base libboost-all-dev
            sudo apt-get clean
            sudo rm -rf /var/lib/apt/lists/*
            mkdir -p $HOME/.local
            if [ ! -d "$HOME/.local/lib" ] ; then 
              curl -skL https://github.com/lballabio/QuantLib/releases/download/QuantLib-v1.14/QuantLib-1.14.tar.gz | tar zxf -
              (cd QuantLib-1.14 ; ./autogen.sh ; ./configure --prefix=$HOME/.local --enable-intraday ; make install)
            fi
      - restore_cache:
          key: 1.14
      - save_cache:
          key: 1.14
          paths: 
            - "$HOME/.local"
